name: Call Reusable Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  call-reusable-workflow:
    uses: mukeshsirvi18/shared-workflow2/.github/workflows/main.yml@main
    with:
      docker_repo_name: 'mukesh18s/prod'
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#run
